# Generated by Django 6.0 on 2025-12-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('precio', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(max_length=555)),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
    ]
